# Generated by Django 4.2.8 on 2023-12-05 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="current_interval",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="current_temperature_2m",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="current_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="current_wind_speed_10m",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="elevation",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="generationtime_ms",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="hourly_relative_humidity_2m",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="hourly_temperature_2m",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="hourly_time",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="hourly_wind_speed_10m",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="longitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="timezone",
            field=models.CharField(default="GMT", max_length=50),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="timezone_abbreviation",
            field=models.CharField(default="GMT", max_length=10),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="utc_offset_seconds",
            field=models.IntegerField(default=0),
        ),
    ]
