# Generated by Django 4.2.8 on 2023-12-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_weatherdata_current_interval_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="current_interval",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="elevation",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="generationtime_ms",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="hourly_relative_humidity_2m",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="hourly_temperature_2m",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="hourly_time",
        ),
        migrations.RemoveField(
            model_name="weatherdata",
            name="hourly_wind_speed_10m",
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="current_humidity_2m",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="current_weather_code",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="daily_precipitation_probability",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="daily_precipitation_sum",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="daily_temperature_2m_max",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="daily_temperature_2m_min",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="daily_time",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="daily_weather_code",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="daily_wind_speed_10m_max",
            field=models.JSONField(default=list),
        ),
    ]
